name: nth-prime
version: 2.1.0.6

dependencies:
  - base

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - containers
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - nth-prime
      - hspec
