name: robot-name
version: 0.1.0.4

dependencies:
  - base
  - mtl
  - containers
  - random
  - streams

library:
  exposed-modules: Robot
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - robot-name
      - hspec
